#ifndef miniXyce_info_hpp
#define miniXyce_info_hpp

#define MINIXYCE_HOSTNAME "diego-Latitude-E7470"
#define MINIXYCE_KERNEL_NAME "'Linux'"
#define MINIXYCE_KERNEL_RELEASE "'4.13.0-38-generic'"
#define MINIXYCE_PROCESSOR "'x86_64'"

#define MINIXYCE_CXX "'/usr/bin/mpicxx'"
#define MINIXYCE_CXX_VERSION "'g++ (Ubuntu 7.2.0-13ubuntu1~16.04.york0) 7.2.0'"
#define MINIXYCE_CXXFLAGS "'-O3 -funroll-all-loops -lpthread  -DBRANCH_HINT=1 -DPRINT_OUTPUT=0 -DCOUNT_QUEUE_DESYNC=0 -DVAR_GROUPING=1 -DAPPROACH_USING_POINTERS=0 -DAPPROACH_ALREADY_CONSUMED=0 -DAPPROACH_NEW_LIMIT=1 -DAPPROACH_WRITE_INVERTED_NEW_LIMIT=0 -DAPPROACH_NEW_ENQ_INDEX=0'"

#endif
